### Get all albums
GET http://localhost:8080/api/albums
Accept: application/json

### Get a album with the given id.
GET localhost:8080/api/albums/1

### Delete a album with the given id.
DELETE localhost:8080/api/albums/9

### Post a new album resource.
POST http://localhost:8080/api/albums
Content-Type: application/json

{"title":"awesome sause","image":"img","recordLabel":"some awesome","artist":"some"}

### Update a album resource.
PUT http://localhost:8080/api/albums
Content-Type: application/json

{"id":1,"title":"sause","image":"img","recordLabel":"some","artist":"person"}

### Update a album's title property.
PATCH http://localhost:8080/api/albums/1/title

John

